<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>jff_csharp_tools_lib_9</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>C# Tools Lib 9</Title>
    <Authors>Josemberg Farias Ferreira</Authors>
    <email>josembergff@gmail.com</email>
    <Description>An open-source project offering a suite of utilities to enhance C# development for .NET Core without MVC version 9.0.0</Description>
    <PackageProjectUrl>https://www.nuget.org/packages/jff_csharp_tools_lib_9</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/josembergff/jff-csharp-tools</RepositoryUrl>
    <NeutralLanguage>en</NeutralLanguage>
    <AssemblyVersion>9.0.0.0</AssemblyVersion>
    <FileVersion>9.0.0.0</FileVersion>
    <Version>2.0.0</Version>
    <PackageTags>tools;c#;custom;basic;dotnetcore</PackageTags>
    <PackageReleaseNotes></PackageReleaseNotes>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\jff-csharp-tools\jff-csharp-tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.15" />
  </ItemGroup>

</Project>
