<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>C# Tools 10</Title>
    <Authors>Josemberg Farias Ferreira</Authors>
    <email>josembergff@gmail.com</email>
    <Description>An open-source project offering a suite of utilities to enhance C# development for .NET Core with MVC version 10.0.0</Description>
    <PackageProjectUrl>https://www.nuget.org/packages/jff-csharp-tools-10</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/josembergff/jff-csharp-tools</RepositoryUrl>
    <NeutralLanguage>en</NeutralLanguage>
    <AssemblyVersion>10.0.0.0</AssemblyVersion>
    <FileVersion>10.0.0.0</FileVersion>
    <Version>1.0.0</Version>
    <PackageTags>tools;c#;custom;basic;dotnetcore</PackageTags>
    <PackageReleaseNotes></PackageReleaseNotes>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\jff-csharp-tools\jff-csharp-tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
  </ItemGroup>

</Project>
